// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// app/layout.js
export default function Layout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}

